######################################################################
# Automatically generated by qmake (2.01a) Tue Sep 28 02:45:38 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . test
INCLUDEPATH += .

# Input
HEADERS += texttools.h cache.h server.h
FORMS += main_window.ui
SOURCES += texttools.cpp cache.cpp server.cpp main.cpp
