######################################################################
# Automatically generated by qmake (2.01a) Sat Sep 25 02:47:15 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
FORMS += main_window.ui
