######################################################################
# Automatically generated by qmake (2.01a) Sun Oct 3 00:24:18 2010
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += importer.h read_file.h importer.h
SOURCES += importer.cpp main.cpp read_file.cpp
